# Generated by Django 3.2.16 on 2022-12-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ArticleType',
            field=models.CharField(choices=[('l', 'Библиотека'), ('5', '5класс'), ('6', '6класс'), ('8', '8класс'), ('9', '9класс'), ('7', '7класс'), ('10', '10класс'), ('11', '11класс')], default='l', max_length=2),
        ),
    ]
